### ISSUE TITLE
Add Haiku Catkeys support to Translate Toolkit, Pootle, and Virtaal

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/translate#1515]
Depends on:
- [x] translate/pootle#1551 Set store meta information on file sync
- [ ] #1737 Drop keys in Haiku Catkeys files when they have no translations
- [x] #1738 Header is not exported for Haiku Catkeys files

_Version: trunk_

This bug deals with support for Catkeys file format (used by Haiku OS) in Translate Toolkit, Pootle, and Virtaal.
