### ISSUE TITLE
[TRACKER] All Mozilla related localisation file managed by moz2po

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#203]
Depends on:

- [ ] #64 Complete handling of accelerator keys for Mozilla
- [x] #68 DTD convert escape to valid characters
- [x] #85 moz2po work directly with Mozilla CVS
- [x] #114 .properties files personalities for Mozilla and Java
- [x] #116 .properties files should honour LOCALIZATION NOTES markings
- [x] #118 browser/defines.inc needs a section uncommented during po2moz
- [x] #120 html2po must wrap multiline extracts in double quotes to make valid PO files
- [x] #121 moz2po will not extract .ini files while recursing
- [x] #127 moz2po should localize searchplugins *.src files
- [x] #131 defines.inc entry MOZ_LANGPACK_CONTRIBUTORS must be localizable
- [ ] #132 mozfunny2po manage installer.inc and installer.it encodings
- [ ] #133 mozfunny2po should handle certain README.txt files
- [ ] #134 Ensure that we can localize Mozilla start pages
- [x] #135 Validate that html2po can convert bookmarks.html in Mozilla source
- [x] #144 Trailing newlines break defines.inc
- [x] #145 po2moz should copy non-PO related files to the target
- [ ] #146 Translatable files with no translations should be copied
- [x] #150 quote.py:mozillapropertiesdecode tries to decode anything with '\N'
- [x] #268 Mozilla DTD and properties files should use automatic comments
- [x] #302 DTD entity wrapping and whitespace
- [x] #307 moz2po couldn't process translation with empty English string properly
- [x] #329 Handle Mozilla pluralForms
- [x] #330 Multiline LOCALIZATION NOTES getting seperated in DTD processing
- [x] #331 Premature termination of DTD elements
- [x] #470 Check created DTD files before writing
- [ ] #471 Review Mozilla accelerator choice

_Version: 0.9a1_

Mozilla has a number of file an idiosyncrosies related to localisation of:
- search
- Start pages
- Google pages
- etc

This is a meta bug to track all these little issues.

The idea is that we will create a bug for each issue and feature request that
related to getting anything and everything that needs localisation done through
moz2po.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
