### ISSUE TITLE
[TRACKER] Speed up build_firefox.sh

### ISSUE THREAD

**Issue by friedelwolff** [translate/translate#2475]
Depends on:
- [x] translate/translate-project#2458 Migrate zaf PO files away from SVN
- [ ] #2471 Upgrade vagrant VM's OS
- [ ] #2472 Separate out once-off functions from build_firefox.sh
- [ ] #2473 Consider pypy for speedups to build_firefox.sh
- [x] #2474 Run build_firefox.sh on a real machine
- [ ] #2487 Build language packs on Indlovu

_Version: trunk_

As part of looking into bug #2253, we identified several possible areas of performance improvements for the build_firefox.sh script and things relating to it. This is a tracker bug for the things that came out of that.

**Comment by nijel** [comment]
The script was removed.
