### ISSUE TITLE
Get tests suite to zero

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#2780]
Depends on:
- [x] #2789 CPO loses obsolete status in obsolete units
- [x] #2790 CPO can't manage setsource where text is not in file encoding
- [x] #2814 tests failing due to dependency on global install
- [x] #2817 search tests fail when no indexing engines available
- [x] #2820 skip tests if required module unavailable

_Version: trunk_

Currently we have a number of failures in the Translate Toolkit tests.  This prevents the following:

1) User or packagers checking that all is OK
2) Code that breaks tests is often missed since tests are in a failed state

The bug is to tackle this as follows:

1) Fix those bugs that are easy
2) Using features of py.test to change the behaviour of the tests if this a platform or missing library issue see pytest.importerskip and pytest.mark.skipif
3) Use xfail to mark tests that we expect to fail where needed so we can fix them at a later date.

There is a branch https://github.com/translate/translate/tree/feature/all_checks_passing which is the effort to get us to zero.

We use Continuous Integration severs at https://travis-ci.org/translate/translate which will be able to automate your tests.
