### ISSUE TITLE
[TRACKER] Toolkit 1.10.0 packaging issues

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#2792]
Depends on:
- [ ] #2793 Langmodels look they are installing in the wrong place
- [ ] #2794 Language models are out of date
- [ ] #2795 Clarify license of stoplist-en
- [x] #2796 Docs jquery is shipped compressed so issue with GPL
- [x] #2797 Fix Sphinx:autodocs Mock errors
- [x] #2798 Manpage auto generation needs update after rST migration of text
- [x] #2799 Clarify license version for toolkit

_Version: trunk_

This is a tracker for all Translate Toolkit 1.10.0 packaging issues identified by packagers such as Fedora and that should be fixed for future releases.
