### ISSUE TITLE
Translate Toolkit GitHub Pull Request backlog

### ISSUE THREAD

**Issue by dupuy** [translate/translate#2899]
Depends on:
- [ ] #2900 Add support for Android plurals
- [x] #2901 Use Qt ts message id attribute if present for getid()
- [ ] #2902 Avoid spurious warnings for UTF-16 encoded .strings files

_Version: trunk_

Ticket for tracking open (or otherwise unresolved) pull requests on https://github.com/translate/translate/pulls
