### ISSUE TITLE
Switch to using cPO (libgettextpo) instead of pypo

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#296]
Depends on:
- [x] #291 Use libgettextpo to parse PO files
- [ ] #297 Implement .copy fully for cPO
- [x] #298 Always output headers in PO files
- [x] #299 Raise errors on failure in cpo
- [x] #300 Ensure cpo works with all non-converter tools
- [x] #308 Implement pounit.getid() for cpo

_Version: 1.0.1_

Switch the toolkit from pypo, the Python PO parser, to using cpo, the parser
that uses libgettextpo from the Gettext package.

This bug tracks all outstanding issues that limit the full switch.

We will need to look at a few cycles of release and testing before we can safely
switch.

Bug #291, tracked the initial implementation before we broke the remaining issues
into their own bugs.
